SHT_NULL = 0x0
SHT_PROGBITS = 0x1
SHT_SYMTAB = 0x2
SHT_STRTAB = 0x3
SHT_RELA = 0x4
SHT_HASH = 0x5
SHT_DYNAMIC = 0x6
SHT_NOTE = 0x7
SHT_NOBITS = 0x8
SHT_REL = 0x9
SHT_SHLIB = 0x0A
SHT_DYNSYM = 0x0B
SHT_INIT_ARRAY = 0x0E
SHT_FINI_ARRAY = 0x0F
SHT_PREINIT_ARRAY = 0x10
SHT_GROUP = 0x11
SHT_SYMTAB_SHNDX = 0x12
SHT_NUM = 0x13
# SHT_LOOS = 0x60000000


# ======================================================================================================================

SHN_UNDEF = 0
SHN_LORESERVE = 0xff00
SHN_LOPROC = 0xff00
SHN_BEFORE = 0xff00
SHN_AFTER = 0xff01
SHN_AMD64_LCOMMON = 0xff02
SHN_HIPROC = 0xff1f
SHN_LOOS = 0xff20
SHN_LOSUNW = 0xff3f
SHN_SUNW_IGNORE = 0xff3f
SHN_HISUNW = 0xff3f
SHN_HIOS = 0xff3f
SHN_ABS = 0xfff1
SHN_COMMON = 0xfff2
SHN_XINDEX = 0xffff
SHN_HIRESERVE = 0xffff

shndx2string = {
    SHN_UNDEF: "UNDEF",
    SHN_LORESERVE: "LORESERVE",
    SHN_LOPROC: "LOPROC",
    SHN_BEFORE: "BEFORE",
    SHN_AFTER: "AFTER",
    SHN_AMD64_LCOMMON: "AMD64_LCOMMON",
    SHN_HIPROC: "HIPROC",
    SHN_LOOS: "LOOS",
    SHN_LOSUNW: "LOSUNW",
    SHN_SUNW_IGNORE: "SUNW_IGNORE",
    SHN_HISUNW: "HISUNW",
    SHN_HIOS: "HIOS",
    SHN_ABS: "ABS",
    SHN_COMMON: "COMMON",
    SHN_XINDEX: "XINDEX",
    SHN_HIRESERVE: "HIRESERVE"
}
